os: arch
init_system: systemd
hostname: archAMD
disk: /dev/nvme0n1

users:
  mislav:
    - wheel
    - audio
    - video
    - storage
    - transmission
    - libvirt

aur_helper: paru
wm: xmonad

git_repos:
  dotfiles:
    https: https://github.com/mislavzanic/dotfiles.git
    ssh: git@github.com:mislavzanic/dotfiles.git

dirs:
  - .config
  - .local/bin
  - .local/share

backup:
  config:
    - alacritty
    - compton
    - config.yaml
    - dmenu
    - doom
    - dunst
    - nvim
    - shell
    - slock
    - sxiv
    - x11
    - xmonad
    - zathura
    - zsh
  local:
    - bin/scripts

packages:
  base:
    - base
    - linux
    - linux-firmware
    - base-devel
    - vim
    - git
    - yq
    - grub
    - dosfstools
    - os-prober
    - mtools
    - efibootmgr
    - networkmanager
    - doas
  pacman:
    - alacritty
    - clang
    - cmake
    - cronie
    - discord
    - dunst
    - emacs
    - exa
    - base-devel
    - feh
    - fzf
    - htop
    - libnotify
    - ttf-symbolia
    - libinput
    - lxappearance
    - maim
    - man-db
    - mpv
    - neofetch
    - neovim
    - network-manager-applet
    - noto-fonts-emoji
    - npm
    - ntfs-3g
    - pamixer
    - pass
    - pavucontrol
    - pulseaudio-alsa
    - starship
    - sxiv
    - thunar
    - transmission-cli
    - ttf-font-awesome
    - ttf-iosevka-nerd
    - ttf-jetbrains-mono
    - ttf-joypixels
    - ttf-liberation
    - ttf-nerd-fonts-symbols
    - ttf-symbola
    - ttf-ubuntu-font-family
    - unzip
    - virt-manager
    - xorg-server
    - xorg-xinit
    - xorg-xprop
    - xclip
    - xdotool
    - xcompmgr
    - youtube-dl
    - zip
    - zathura
    - zathura-pdf-mupdf
    - zsh
    - zsh-autosuggestions
    - zsh-syntax-highlighting
  aur:
    - brave-bin
    - gtk-theme-arc-gruvbox-git
    - libxft-bgra-git
    - spotify
    - stack-static
    - tremc
